#!/bin/bash
alias man='man -a'

alias pckimmo='LC_ALL=fi_FI LANG=fi_FI luit pckimmo'

alias nisudo='sudo nice'

alias svim='sudo vim'

alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'

alias diff='diff -u'

# upstream won't correct locale handling bugs
alias rrip_gui='LC_ALL=C rrip_gui'
alias rrip_cli='LC_ALL=C rrip_cli'

# apt-cache search is overly eager
apt-search() {
    apt-cache search $@ | fgrep $@
}

debugmake() {
	dbgflags="-g -pg -fno-inline"
	CFLAGS="${CFLAGS} ${dbgflags}" CXXFLAGS="${CXXFLAGS} ${dbgflags}" make $@
}

backup() {
	mv $1 $1~
}

eskel() {
	cp /usr/portage/skel.ebuild ./$1.ebuild
	cp /usr/portage/skel.ChangeLog ./ChangeLog
	cp /usr/portage/skel.metadata.xml ./metadata.xml
	LC_ALL=C sed -i -e "s/<PACKAGE_NAME>-<PACKAGE_VERSION>-<PACKAGE_RELEASE>/$1/g" \
		-e "s/DD MMM YYYY/$(date '+%d %b %Y')/g" \
		-e 's/YOUR_NAME/Flammie Pirinen/g' \
		-e 's/YOUR_EMAIL/flammie@gentoo.org/g' ChangeLog
	sed -i -e 's/>@gentoo.org/>flammie@gentoo.org/g' metadata.xml
}

etest() {
	ebuild $1 unpack && ebuild $1 compile && ebuild $1 install
}
# vim: set ft=sh
