#!/bin/bash
alias man='man -a'

alias pckimmo='LC_ALL=fi_FI LANG=fi_FI luit pckimmo'

alias nisudo='sudo nice'

alias svim='sudo vim'

alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'

alias diff='diff -u'

alias grep='grep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias egrep='egrep --colour=auto'

# upstream won't correct locale handling bugs
alias rrip_gui='LC_ALL=C rrip_gui'
alias rrip_cli='LC_ALL=C rrip_cli'

# programmer's sort
alias csort='LC_ALL=C sort'

# vim less
alias vähemmän='/usr/share/vim/vim??/macros/less.sh'
alias vless='/usr/share/vim/vim??/macros/less.sh'

# apt-cache search is overly eager
apt-search() {
    apt-cache search $@ | fgrep $@
}

debugmake() {
	dbgflags="-g -pg -fno-inline"
	CFLAGS="${CFLAGS} ${dbgflags}" CXXFLAGS="${CXXFLAGS} ${dbgflags}" make $@
}

remake() {
    if test -f $1 ; then
        rm -v -f $1
    elif test -d $1 ; then
        rm -v -rf $1
    fi
    make $1
}

backup() {
	cp -v $1 $1~
}

frontdown() {
    cp -v $1~ $1
}

eskel() {
	cp /usr/portage/skel.ebuild ./$1.ebuild
	cp /usr/portage/skel.ChangeLog ./ChangeLog
	cp /usr/portage/skel.metadata.xml ./metadata.xml
	LC_ALL=C sed -i -e "s/<PACKAGE_NAME>-<PACKAGE_VERSION>-<PACKAGE_RELEASE>/$1/g" \
		-e "s/DD MMM YYYY/$(date '+%d %b %Y')/g" \
		-e 's/YOUR_NAME/Flammie Pirinen/g' \
		-e 's/YOUR_EMAIL/flammie@gentoo.org/g' ChangeLog
	sed -i -e 's/>@gentoo.org/>flammie@gentoo.org/g' metadata.xml
}

etest() {
	ebuild $1 unpack && ebuild $1 compile && ebuild $1 install
}

grepless() {
    fgrep --colour=always $@ | less -R
}

egrepless() {
    fgrep --colour=always $@ | less -R
}

fgrepless() {
    fgrep --colour=always $@ | less -R
}

# vim: set ft=bash
